### ISSUE TITLE
double click to an eeg file, opens a new window, then next double click gives an error that the file does not exist

### ISSUE THREAD

**Issue by jezekp** [dorianb96/EEG_WorkflowGUI#2]
How to reproduce this problem:
1. Start the app
2. double click to any folder
3. click to any file
4. in the last window click to the file again

The error looks like:

![snimek obrazovky porizeny 2017-08-25 15-30-45](https://user-images.githubusercontent.com/1769981/29734988-6b150ec2-89aa-11e7-9f1d-c168009afd70.png)

**Comment by dorianb96** [comment]
Fixed in this commit: https://github.com/dorianb96/EEG_ClientGUI/commit/eb630e8e9bdeafea72764d12725834af6be84ad0
