### ISSUE TITLE
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: -1 if I click to the next/back button and no file is chosen

### ISSUE THREAD

**Issue by jezekp** [dorianb96/EEG_WorkflowGUI#4]
When the gui is opened and the next button is clicked the error:
java.lang.ArrayIndexOutOfBoundsException: -1 appears

**Comment by dorianb96** [comment]
Fixed in this commit: https://github.com/dorianb96/EEG_ClientGUI/commit/eb630e8e9bdeafea72764d12725834af6be84ad0
