### ISSUE TITLE
When I click to NO in yes-no dialog when I'm closing the job it is closed anyway

### ISSUE THREAD

**Issue by jezekp** [dorianb96/EEG_WorkflowGUI#5]

**Comment by dorianb96** [comment]
Fixed in this commit: https://github.com/dorianb96/EEG_ClientGUI/commit/eb630e8e9bdeafea72764d12725834af6be84ad0

**Comment by jezekp** [comment]
It works better now, but if I click to YES, I got a message job xx is done. Hovewer in the case when I cancel the job, I thing this message is redundant

**Comment by dorianb96** [comment]
Fixed in this commit: https://github.com/dorianb96/EEG_ClientGUI/commit/d5e885907d6087d9af55b9d36fc5c803705bd7c1

**Comment by jezekp** [comment]
job results -> results
classifiers -> clasifiers
